# Generated by Django 4.1.1 on 2023-02-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibitor", "0003_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
