# Generated by Django 4.1.6 on 2023-02-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibitor", "0003_user_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="exhibition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("presence_User", models.BooleanField(default=False)),
                ("presence_moc", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="MOC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=20)),
                ("poster", models.ImageField(upload_to="posters")),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="author",
        ),
        migrations.RemoveField(
            model_name="user",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="user",
            name="published_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="text",
        ),
        migrations.RemoveField(
            model_name="user",
            name="title",
        ),
        migrations.AddField(
            model_name="user",
            name="email_adress",
            field=models.EmailField(default=True, max_length=30),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="nick",
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default=True, max_length=12),
        ),
        migrations.AddField(
            model_name="user",
            name="surname",
            field=models.CharField(default=True, max_length=20),
        ),
    ]
