# Generated by Django 4.1.6 on 2023-02-20 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "exhibitor",
            "0005_alter_user_options_remove_user_nick_user_date_joined_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="moc",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
