# Generated by Django 4.1.6 on 2023-02-26 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exhibitor", "0006_alter_moc_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moc",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="all_moc",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="moc",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="posters"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=20, unique=True),
        ),
    ]
