# Generated by Django 4.1.6 on 2023-02-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibitor", "0008_alter_moc_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="moc",
            name="category",
            field=models.CharField(
                choices=[
                    (7, "Kolejnictwo"),
                    (2, "Militaria"),
                    (0, "Castle/Starożytność"),
                    (5, "Space/Sci-fi"),
                    (1, "Komiks/Anime/Manga"),
                    (3, "Pojazdy minifig"),
                    (4, "Pojazdy Technic"),
                    (6, "Architektura"),
                ],
                default=1,
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="moc",
            name="size",
            field=models.CharField(
                choices=[
                    (5, "3 stoły"),
                    (2, "1,5 stołu"),
                    (4, "2,5 stołu"),
                    (1, "1 stół"),
                    (0, "0,5 stołu"),
                    (3, "2 stoły"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
