# Generated by Django 4.1.6 on 2023-03-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibitor", "0011_moc_size_alter_moc_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moc",
            name="size",
            field=models.FloatField(
                choices=[(0.5, "0,5 stołu"), (1, "1 stół"), (2, "2 stoły")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_adress",
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="user",
            name="surname",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
