# Generated by Django 4.1.6 on 2023-03-22 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exhibitor", "0013_remove_exhibition_presence_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organizator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=20)),
                ("imię", models.CharField(max_length=20)),
                ("nazwisko", models.CharField(max_length=20)),
                ("ulica", models.CharField(max_length=20)),
                ("miasto", models.CharField(max_length=20)),
                ("kod_pocztowy", models.CharField(max_length=20)),
                ("NIP", models.CharField(max_length=20)),
                ("telefon", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name="exhibition",
            name="principal",
        ),
        migrations.AddField(
            model_name="exhibition",
            name="organizator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="exhibitor.organizator",
            ),
            preserve_default=False,
        ),
    ]
